### ISSUE TITLE
老师, QQ群解散了嘛, 我是在实验楼/蓝桥云课过来的

### ISSUE THREAD

**Issue by KongFanJin** [loveyacper/Qedis#16]
https://www.[lanqiao.cn/courses/1341](https://www.lanqiao.cn/courses/1341)

**Comment by loveyacper** [comment]
> [https://www.[lanqiao.cn/courses/1341](https://www.lanqiao.cn/courses/1341)](https://www.%5Blanqiao.cn/courses/1341%5D(https://www.lanqiao.cn/courses/1341))

855124661
