### ISSUE TITLE
现在集群的开发进度是怎样呢？

### ISSUE THREAD

**Issue by seahime** [loveyacper/Qedis#7]

**Comment by loveyacper** [comment]
两年前休陪产假的时候，完成了使用zookeeper的选主，本质上类似于redis-sentinel的功能。
支持sharding的分布式集群，在2017年底实现了一部分，不过这1年半都没有维护开发了。
我都想把sharding这一部分代码删除了，好乱

**Comment by seahime** [comment]
我在读代码的时候看到，proxy和qedis-server需要的配置文件应该是不一样的，方便提供一个proxy的示例配置文件么？

**Comment by loveyacper** [comment]
proxy其实是为sharding的，只是选主failover的话，就在`QSentinel`目录下。
`cluster`目录的完成度比较低，单独编译的，使用了一个独立的net库ananas。
功能大概只是做了从zk发现服务，proxy路由转发redis命令到服务，再把响应转给客户端。迁移啥的都没有。
建议别看了，后期有时间打算重来，也不一定选择cpp写。
另外你说的配置，查看下文件[ProxyConfig.cc](cluster/qedis_proxy/ProxyConfig.cc)，就三项简单的配置：绑定地址，日志目录，zk地址。其中zk地址还写死了都没后续变更了:(

**Comment by seahime** [comment]
感谢解答，也非常感觉分享出代码供学习

**Comment by seahime** [comment]
我启动了 server * 3 (setid=1,2,3), proxy * 1 (port=6379), zookeeper * 1，使用redis-cli测试时，有如下的反应：

> $ ./redis-cli 
127.0.0.1:6379> set name cyril
(error) ERR Server not ready
127.0.0.1:6379> info
TODO_INFO127.0.0.1:6379> 

这个是当前正常的显示，还是我配置错了呢？
